// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteChatSession(arg1) {
  return window['go']['main']['App']['DeleteChatSession'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function LoadChatSessions(arg1) {
  return window['go']['main']['App']['LoadChatSessions'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveChatSession(arg1, arg2) {
  return window['go']['main']['App']['SaveChatSession'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function TerminalCommand(arg1) {
  return window['go']['main']['App']['TerminalCommand'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
