// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteChatSession(arg1:string):Promise<void>;

export function GetChatSessionPath(arg1:string,arg2:string):Promise<string>;

export function ListFiles(arg1:string):Promise<Array<main.FileInfo>>;

export function LoadChatSessions(arg1:string):Promise<Array<main.ChatFile>>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveChatSession(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function ShowConfirmationDialog(arg1:string,arg2:string):Promise<string>;

export function TerminalCommand(arg1:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
